#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure|failed-upgrade)
        if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
            systemctl daemon-reload
        fi
        ;;
esac

exit 0
